swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /task:
    get:
      operationId: task.request
      tags:
        - Task
      summary: The task input structure supported by the server application
      description: Read the information necessary to get a task
      parameters:
        - name: domainId
          in: query
          description: ID of the domain requesting a task
          type: integer
          required: True
      responses:
        200:
          description: Successful read task operation
          schema:
            type: object
  /register:
    post:
      operationId: domain.register
      tags:
        - Domain
      summary: Register a new domain in the repository
      description: Register a new domain in the repository
      parameters:
        - name: domain
          in: body
          description: Information describing the domain composition
          required: True
          schema:
            type: array
      responses:
        200:
          description: Successful register domain operation
          schema:
            type: object
            properties:
              id:
                type: integer
  /report:
    post:
      operationId: task.report
      tags:
        - Report
      summary: Report the output of a task
      description: Report the output of a task
      consumes:
        - multipart/form-data
      parameters:
        - name: domainId
          in: query
          description: The domain ID
          required: True
          type: integer
        - name: taskId
          in: query
          description: The task ID
          required: True
          type: integer
        - name: outputFile
          in: formData
          type: file
          description: The file with the results of the task.
      responses:
        200:
          description: Successful report operation